// <auto-generated />
using System;
using Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251105112259_InitBrands")]
    partial class InitBrands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Brand", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Brands.BrandAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "Alias")
                        .IsUnique();

                    b.ToTable("BrandAlias", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Brands.Country", b =>
                {
                    b.Property<string>("Code2")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Code3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("FlagEmoji")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NameFa")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Code2");

                    b.HasIndex("Code3")
                        .IsUnique();

                    b.HasIndex("NameEn");

                    b.ToTable("Country", "catalog");

                    b.HasData(
                        new
                        {
                            Code2 = "IR",
                            Code3 = "IRN",
                            FlagEmoji = "🇮🇷",
                            NameEn = "Iran",
                            NameFa = "ایران",
                            Region = "Asia"
                        },
                        new
                        {
                            Code2 = "TR",
                            Code3 = "TUR",
                            FlagEmoji = "🇹🇷",
                            NameEn = "Türkiye",
                            NameFa = "ترکیه",
                            Region = "Asia"
                        },
                        new
                        {
                            Code2 = "DE",
                            Code3 = "DEU",
                            FlagEmoji = "🇩🇪",
                            NameEn = "Germany",
                            NameFa = "آلمان",
                            Region = "Europe"
                        },
                        new
                        {
                            Code2 = "US",
                            Code3 = "USA",
                            FlagEmoji = "🇺🇸",
                            NameEn = "United States",
                            NameFa = "آمریکا",
                            Region = "Americas"
                        },
                        new
                        {
                            Code2 = "CN",
                            Code3 = "CHN",
                            FlagEmoji = "🇨🇳",
                            NameEn = "China",
                            NameFa = "چین",
                            Region = "Asia"
                        },
                        new
                        {
                            Code2 = "JP",
                            Code3 = "JPN",
                            FlagEmoji = "🇯🇵",
                            NameEn = "Japan",
                            NameFa = "ژاپن",
                            Region = "Asia"
                        },
                        new
                        {
                            Code2 = "IT",
                            Code3 = "ITA",
                            FlagEmoji = "🇮🇹",
                            NameEn = "Italy",
                            NameFa = "ایتالیا",
                            Region = "Europe"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentBlocksJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultSlug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Icon")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSlug")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Category", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Categories.CategoryClosure", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("DescendantId");

                    b.ToTable("CategoryClosure", "catalog");
                });

            modelBuilder.Entity("Catalog.Domain.Brands.Brand", b =>
                {
                    b.HasOne("Catalog.Domain.Brands.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Brands.BrandAlias", b =>
                {
                    b.HasOne("Catalog.Domain.Brands.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Categories.Category", b =>
                {
                    b.HasOne("Catalog.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Catalog.Domain.Categories.CategoryClosure", b =>
                {
                    b.HasOne("Catalog.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
